### ISSUE TITLE
navigation is broken on mobile

### ISSUE THREAD

**Issue by brunoamaral** [brunoamaral/gregory#137]

**Comment by dippas** [comment]
I'll gladly can take care of this @brunoamaral

**Comment by dippas** [comment]
@brunoamaral  apparently for some reason it is not compiling the class `.nav-open` from `.scss` to `.css` in any file

**Comment by brunoamaral** [comment]
That makes sense, I was changing the postcss config around the same time I moved the site into the `hugo/` directory. 

Obrigado! 😁
