### ISSUE TITLE
Issues with 'break' statement and Python 3.10

### ISSUE THREAD

**Issue by brunomiguel** [brunoamaral/gregory#151]
Python 3.10 complains about the `break` statement being outside of the loop when running setup.py. A way around this is using `raise Exception("Message")`. I don't have a previous Python 3 version to test, but I assume it works with previous ones.

**Comment by brunoamaral** [comment]
To be fair, the whole setup.py script needs to be reviewed. Gregory now uses docker containers to run node-red, django, and postgres. All the setup needed is to make sure the directories exist, commands are installed, and that we run  `./manage.py makemigrations && ./manage.py migrate`.

**Comment by brunoamaral** [comment]
Tried setting up the project with Python 3.10.4 and `pip install -r requirements.txt` fails. 

```
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
      You should consider upgrading via the '/Users/brunoamaral/Labs/gregory/env3.10/bin/python3.10 -m pip install --upgrade pip' command.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.
```
