### ISSUE TITLE
Hardcoded Hugo path

### ISSUE THREAD

**Issue by brunomiguel** [brunoamaral/gregory#152]
On several Linux distributions, Hugo is installed to /usr/bin, but setup.py has the path hardcoded. Could you change it to the way it detects docker-compose?

**Comment by brunoamaral** [comment]
Can you please see if the new branch fixes it?

**Comment by brunomiguel** [comment]
Sorry, I wasn't able to test it. I'll try it during this week if I can but, looking at the PR, all looks good
