### ISSUE TITLE
when saving links, gregory should remove utm parameters from URL

### ISSUE THREAD

**Issue by brunoamaral** [brunoamaral/gregory#254]
`https://pubmed.ncbi.nlm.nih.gov/36188625/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=10guX6I3SqrbUeeLKSTD6FCRM44ewnrN2MKKTQLLPMHB4xNsZU&fc=20210216052009&ff=20221003070011&v=2.17.8`

Should be

`https://pubmed.ncbi.nlm.nih.gov/36188625/`

**Comment by antoniolopes** [comment]
Should it remove all query args or just the "utm_" ones?

**Comment by brunoamaral** [comment]
I was going to say all, but then I remembered there is a risk of some websites having weird links where they point to the article via `?article_id=123`.

**Comment by antoniolopes** [comment]
This solves it:

``` python
import sys
from urllib.parse import urlencode, urlparse, urlunparse, parse_qs

url = 'https://pubmed.ncbi.nlm.nih.gov/36188625/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=10guX6I3SqrbUeeLKSTD6FCRM44ewnrN2MKKTQLLPMHB4xNsZU&fc=20210216052009&ff=20221003070011&v=2.17.8'
u = urlparse(url)
query = parse_qs(u.query, keep_blank_values=True)
query.pop('utm_source', None)
query.pop('utm_medium', None)
query.pop('utm_campaign', None)
query.pop('utm_content', None)
u = u._replace(query=urlencode(query, True))
print(urlunparse(u))
```

**Comment by brunoamaral** [comment]
I'll get on it ASAP 😁
