### ISSUE TITLE
Articles Dashboard, Subject filter error

### ISSUE THREAD

**Issue by redtruck99** [brunoamaral/gregory#390]
1. Clicked Subject,  Multiple Sclerosis was the only item on the list.
2. Checked the box, clicked Add filter.
3. Six on the display boxes reported: "There was a problem displaying this chart"
This may because there were no papers? But it is confusing to the user that Multiple Sclerosis was the option, and no results.

**Comment by brunoamaral** [comment]
@redtruck99 thank you for letting me know! 

Just finished taking a look and applying corrections. https://metabase.gregory-ms.com/public/dashboard/39cbe602-4d42-46af-bfe4-0de04ef5e5f9?published_date=&subject=Multiple%20Sclerosis&filter_by_topic_%252F_category=&title_contains=&manual_selection=&full_name_contains..._(case_sensitive)=&author_given_name=&family_name=&access=

Quick update:
- right now, MS is the only subject configured
- on my laptop, there's already a working version for multiple subjects and possibility of using different ML models per subject.

Going to close the issue but feel free to comment with more information or any questions.
